#ifndef CONST_HPP
#define CONST_HPP

#define TAILLE_CASE 32
#define TAILLE_CASE_MINI_CARTE 8
#define TAILLE_PERSONNAGE 64
#define TAILLE_PERSONNAGE_MINI_CARTE 30
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define CAM_WIDTH WINDOW_WIDTH / 1.5
#define CAM_HEIGHT WINDOW_HEIGHT / 1.5
#define DEPLACEMENT 5
#define ANIMATION_SPEED 100
#define NUM_FRAMES 9
#define COULEUR_CIEL Color(135, 206, 250)
#define TITRE_FENETRE "jeu"

#define INVENTORY_HEIGHT 4
#define INVENTORY_WIDTH 9
#define INVENTORY_TILE_SIZE 50
#define INVENTORY_OBJECT_SIZE 32

#endif